version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  continue:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            apps/frontend/.* run-frontend-workflow true
            apps/backend/.* run-backend-workflow true
          base-revision: master
          config-path: .circleci/config.yml